version: '3.8'
services:
  mysql:
    image: mysql:8.0.31
    command: "mysqld --character-set-server=utf8mb4"
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: lalaplate
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      MYSQL_ROOT_HOST: '%'
    ports:
      - "13306:3306"
  redis-cluster:
    image: grokzen/redis-cluster:6.2.1
    environment:
      IP: '127.0.0.1'
      INITIAL_PORT: 8000
    ports:
      - '8000-8005:8000-8005'
  mongo:
    image: mongo:5.0.5
    ports:
      - "37018:27017"