spring:
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/lalaplate?serverTimezone=Asia/Seoul
    username: local
    password: local
  data:
    mongodb:
      uri: mongodb://localhost:37018
      database: lalaplate
    redis:
      timeout: 3000ms
      connect-timeout: 3000ms
      cluster:
        nodes: localhost:8000
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 60s
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

  task:
    execution:
      thread-name-prefix: Async-
      pool:
        max-size: 16
        queue-capacity: 50
        keep-alive: 1s

app:
  crypto-key:
    attribute-encrypt-key: xf6sDkpae4cYeR3YJn0VJQ8bRbvqLohx
    iv: jHcGcPePw95wiXcANyb8FGfvjDOGTPQB

  client:
    payment:
      host: http://localhost:8090
      timeout: 2
      logging: true
      use-dummy: true
    ex-rate:
      host: https://open.er-api.com/
      timeout: 2
      logging: true
      use-dummy: false